<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    @include('htmlHead')

    <body>
        <div class="flex-center position-ref">
            <div class="content">
                
                <br><br><br><br>
                
                <a href="{{ url('/') }}"><img src="img/Logo.png" alt=""></a>

                <div style="padding: 5%; text-align: justify; color:#fff;">
                    
                    <h2><u>What is i<span style="font-style: italic;">Decide</span> ?</u></h2>
                    <h4>
                        &ensp;&ensp;i<span style="font-style: italic;">Decide</span> is a recommendation system - built by laravel framework - for students who finished or about to finish high school and want to join a university to start a degree program. It helps them to decide what major program is best for them based on certain data required to be entered and analyzed. The recommendation process is machine-learning based, using online API tool called "Recombee". i<span style="font-style: italic;">Decide</span> provides a new approach to help students deciding, as the only common approaches now are about reading a lot of related articles and written resources or to consult some other individuals who might have an opinion about the issue. As this was an FYP, the software was scooped down to prioritize 3 recommendations only (ICT / Engineering / Architecture).
                    </h4>
                    
                    <br><br>
                    
                    <div class="row">
                        <div class="col-md-5"><br><br><a target="_blank" href="img/fyp1.jpg"><h3 style="text-align:center;"><img src="img/fyp1.jpg" width="50%" alt=""><br><br>FYP 1 Poster</h3></a></div>
                        <div class="col-md-2"></div>
                        <div class="col-md-5"><br><br><a target="_blank" href="img/fyp2.jpg"><h3 style="text-align:center;"><img src="img/fyp2.jpg" width="50%" alt=""><br><br>FYP 2 Poster</h3></a></div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="col-md-4"><br><br><a target="_blank" href="/finalreport.pdf"><h3 style="text-align:center;"><img src="img/finalreport.jpg" width="50%" alt=""><br><br>FYP Final Report</h3></a></div>
                        <div class="col-md-4"></div>
                    </div>

                    <br><br>

                    <h2><u>Why is i<span style="font-style: italic;">Decide</span> important ?</u></h2>
                    <h4>
                         &ensp;&ensp;It is noticeable that many students finish high school and pick their degree program based on fault approaches. Many statistics show the unsatisfactory of graduates for the major decision they made. According to ‘Inside High Ed’ survey, %40 of students regrets their major choice and say that they would choose different one if they got the chance. The end result of this disappointment that %80 of U.S. college students decide a major change at least once, or to drop what was studied in the bachelor and start an irrelevant career like %73 of graduates in the U.S. There is a big number of causes for that fault pickup process, like the stress and anxiety generated by the feeling of how big and important the major decision is, the ignorance of student-character factor in the choosing process, the awareness and responsibility level of the students at the time of making the decision, self-awareness, egoism and self-absorbing, parental influence, ill-advise, the blindness about the available major choices, the wrong impression about some majors and many more reasons.
                    </h4>
                </div>

            </div>
        </div>
    </body>
</html>